### ISSUE TITLE
Schedules: Save only date without time (start date and end date)

### ISSUE THREAD

**Issue by EleonoraPetzold** [bexis/Module_ResourceManagement#111]
We don't need the time info and sometimes we have trouble to work with these times e.g. comparison.

**Comment by EleonoraPetzold** [comment]
Store only date with time if the date picker allow the user to select time.

**Comment by aostrow** [comment]
#211 may be affected

**Comment by EleonoraPetzold** [comment]
This issue doesn't matter for now. Maybe if we refactor the UI
