### ISSUE TITLE
500 Error on Server - person party information missing

### ISSUE THREAD

**Issue by geofranzi** [bexis/Module_ResourceManagement#116]
http://be2020-dev.inf-bb.uni-jena.de:2020/RBM/Schedule/AddResourceToCart

-> catch user profile is empty / not filled

**Comment by EleonoraPetzold** [comment]
warst du da eingeloggt? Aber das Modul ist ja in der regel nicht öffentlich und man kann nicht ohne eingeloggt sein drin was machen. Könnte man trotzdem man abfangen...

**Comment by geofranzi** [comment]
Da ging’s aber glaube darum das man eingeloggt ist, aber das Profil noch nicht gefüllt hat. Das es gefüllt ist können wir nicht erzwingen.

**Comment by EleonoraPetzold** [comment]
ah ok, die party ist damit nicht angelegt. ich weiß jetzt was gemeint ist. Da müssen wir es unbedint abfangen.
