### ISSUE TITLE
Test 2021-01 (simultaneously)

### ISSUE THREAD

**Issue by aostrow** [bexis/Module_ResourceManagement#122]
Testen des Feldbuches um abzuschätzen, ob es "reif" ist.

Einträge aus B1 mit Enddate > 2020 sind hier im svn: ...\workCopy\ProjectFiles\BExIS2\BExIS2 Migration\fieldbookGT2020.txt

**Comment by EleonoraPetzold** [comment]
Ergebnisse:

- Bei dem gleichzeitigen klicken auf "Book" ist es möglichen Ressourcen > der Quantity zu buchen. 
-

**Comment by EleonoraPetzold** [comment]
Test done.
Move the issue to #161
