### ISSUE TITLE
Show person name for resources (schedules) in calendar

### ISSUE THREAD

**Issue by EleonoraPetzold** [bexis/Module_ResourceManagement#125]
reserved by or contact -> need to be discussed.

**Comment by geofranzi** [comment]
? Entwerder ich zeig den Namen der Buchung oder der Ressouce ...wo soll da ein Name hin, wo der Platz eh schon beengt ist?

**Comment by EleonoraPetzold** [comment]
so wie hier im alten Feldbuch. 
![image](https://user-images.githubusercontent.com/42029171/103645110-c7564180-4f57-11eb-8bbc-068e7a908eba.png)

Wir haben aber auch gesagt das wir noch mal mit den LMTs abbrechen ob sie das genutzt haben und brauchen.
Wenn auch nur für schedules nicht für event. Im event können das ja unterschiedliche Personen sein.

**Comment by geofranzi** [comment]
es hat aber noch keiner rausgefunden, wie und ob wir dort einen Zeilenumbruch hinbekommen. Ich glaube es ging nicht so richtig und von daher würde ich jetzt nicht irgendwelche Versprechungen irgendwem machen ...

**Comment by geofranzi** [comment]
![Uploading image.png…]()

**Comment by geofranzi** [comment]
![image](https://user-images.githubusercontent.com/15946467/104110014-ce70ad00-52d3-11eb-850c-b048519b8a67.png)
