### ISSUE TITLE
Check availability - don't work if not available

### ISSUE THREAD

**Issue by EleonoraPetzold** [bexis/Module_ResourceManagement#129]
Hatten wir das mit Absicht ausgeschaltet? 
Erst mal ganz rausnehmen solange es nicht 100% funktioniert?

**Comment by geofranzi** [comment]
also bei mir wirds "rot" beim draufklicken ...

![image](https://user-images.githubusercontent.com/15946467/103648940-efe13a00-4f5d-11eb-95b2-e3c053524f4e.png)

**Comment by EleonoraPetzold** [comment]
rot ja aber eigentlich war es angedacht das sich dann ein Fenster mit alternativen öffnet. wir haben uns dann erinnert das das nicht richtig ging und haben das erst mal rausgenommen ... ich muss auch mal dazu die commits anschauen.

**Comment by EleonoraPetzold** [comment]
dazu auch https://github.com/bexis/Module_ResourceManagement/issues/7

**Comment by geofranzi** [comment]
ja es ging nicht und da wurde bzw da können wir nichts sinnvolles anzeigen, da uns die Semantik fehlt.

**Comment by EleonoraPetzold** [comment]
erst mal rausnehmen den button
