### ISSUE TITLE
Add additional resource with quantity/edit with resource quantity fails

### ISSUE THREAD

**Issue by geofranzi** [bexis/Module_ResourceManagement#133]
![image](https://user-images.githubusercontent.com/15946467/104423091-ea977700-557d-11eb-94ba-f10374f0e525.png)

**Comment by bayramliaziz** [comment]
- Add a resource and click continue booking
- Click Add more Resources
- Add a resource with a limited quantity ( e.g. Chest freezer (SCH) )
- Fill the required fields 
- Click Book

Result: 
![image](https://user-images.githubusercontent.com/66725469/105893468-6af4b800-6013-11eb-84c8-051ac65ba223.png)

**Comment by EleonoraPetzold** [comment]
granter then 0 is for me not reproducible. But for the second way there is another bug:
![image](https://user-images.githubusercontent.com/42029171/105957373-75499d00-6079-11eb-86d8-547e5e8f109a.png)

with edit the resource is not available
