### ISSUE TITLE
delete icon on a resource without edit

### ISSUE THREAD

**Issue by bayramliaziz** [bexis/Module_ResourceManagement#134]
- Book two resources in one booking
- Click on the booking from the calendar or the list
- Delete icons are visible on resources
- Click delete icon and resource is removed from the UI 
- After refreshing the page, removed resource comes back again

![delete_icon](https://user-images.githubusercontent.com/66725469/104743519-1405fd80-574c-11eb-8231-4e8a62208822.png)

**Comment by EleonoraPetzold** [comment]
Delete schedule directly after click from event.

**Comment by EleonoraPetzold** [comment]
We remove the button and delete schedule directly after click
