### ISSUE TITLE
booking error with add more resources

### ISSUE THREAD

**Issue by bayramliaziz** [bexis/Module_ResourceManagement#136]
- Add one resource and click continue booking 
- Click Add more Resources
- Add one more resource and click continue booking
- Delete the first added resource and click Add more Resources
- Add one more resource and click continue booking
- Fill the required fields and click Book

Result: 
- The third added resource detail bar doesn't extend when you click and the details are not editable 
- After clicking book name of the third resources changes and becomes as the second one, also the resources are not booked

![image](https://user-images.githubusercontent.com/66725469/104749475-259ed380-5753-11eb-939a-de202bccabf6.png)

**Comment by EleonoraPetzold** [comment]
This two schedule has some index
