### ISSUE TITLE
booking limited resource multiple times

### ISSUE THREAD

**Issue by bayramliaziz** [bexis/Module_ResourceManagement#145]
- Book a resource with quantity 1 ( e.g. Chest freezer (SCH)) with dates e.g 10.xx.xxxx - 31.xx.xxxx
- Book the same resource again with dates e.g. 19.xx.xxx - 25.xx.xxxx

Result: 

- The resource is booked multiple times even it has a quantity of one 

![image](https://user-images.githubusercontent.com/66725469/105902786-66360100-601f-11eb-86cb-e9026b0dde41.png)

**Comment by EleonoraPetzold** [comment]
This should be fixed with the last code updates ...

**Comment by EleonoraPetzold** [comment]
Please test again with updated code, thanks!

**Comment by bayramliaziz** [comment]
> 
> 
> Please test again with updated code, thanks!

I tested with the updated code and now it works. Thanks.
