### ISSUE TITLE
 Remove the last comma

### ISSUE THREAD

**Issue by EleonoraPetzold** [bexis/Module_ResourceManagement#156]
![image](https://user-images.githubusercontent.com/42029171/107341516-62928780-6abf-11eb-8584-cf980d9a1d76.png)

**Comment by EleonoraPetzold** [comment]
![image](https://user-images.githubusercontent.com/42029171/108045757-1eb1fc00-7044-11eb-8efe-ab72f17640b3.png)
 for user, too

**Comment by geofranzi** [comment]
https://github.com/bexis/Module_ResourceManagement/commit/7f51a871905ce80cedf82ec3e04e040c1fae724a
