### ISSUE TITLE
Calendar List view: "Show with history" as button

### ISSUE THREAD

**Issue by EleonoraPetzold** [bexis/Module_ResourceManagement#159]
It is not apparent that you can click there, we need a button or checkbox

![image](https://user-images.githubusercontent.com/42029171/107497223-95598000-6b92-11eb-915b-1bd87b55fbad.png)

**Comment by geofranzi** [comment]
It is known ...I think it also already somewhere in a ticket

**Comment by EleonoraPetzold** [comment]
there is already an issue for that problem #101
