### ISSUE TITLE
Number of selectable ressources should be = max number of ressource

### ISSUE THREAD

**Issue by CFuerstenau** [bexis/Module_ResourceManagement#162]
Right now you can add as many sleeping places to the cart (Selected Resources) as you wish
It should be only possible to put the max number of sleeping places to the cart.

![grafik](https://user-images.githubusercontent.com/45873895/107772713-e0af9200-6d3c-11eb-8f92-17b073fc5fa0.png)

**Comment by EleonoraPetzold** [comment]
But you don't have a guarantee that you will get it. real availability cannot be checked without a period of time.
you can also put in more than available and book different periods. 
I wouldn't limit the resource cart.

**Comment by geofranzi** [comment]
I also would not limit it as it can be just distributed over time. There is no need for extra limits.
