### ISSUE TITLE
Confirm information file only once per file 

### ISSUE THREAD

**Issue by CFuerstenau** [bexis/Module_ResourceManagement#172]
Would be nice, if the same file only has to be confirmed once, e.g.

- sleeping places in HAI and Alb (here it's possible to confirm all sleeping places by "Copy filled values to all other")
- different areas in SCH ("Copy does't work here)

**Comment by CFuerstenau** [comment]
I think this would still be a good enhancement.

**Comment by aostrow** [comment]
Currently it works for the same resource. But we could switch to the same file.

Check, if the same files are there and copy the checkmark over to all resources where the file is listened.

**Comment by aostrow** [comment]
Does not work for the same file. 
![grafik](https://github.com/bexis/Module_ResourceManagement/assets/26480843/03972c26-1c04-4b1e-b8cf-a57979c72d9e)

**Comment by aostrow** [comment]
Works better now but not perfect.

For the first same resource, it is working.  But if you have more than two same resources in your event and do it for the second resource, it does not work. It removes the entry for the first (of the second) resources and keep it for the second (of the second) resources. See also image.

![grafik](https://github.com/bexis/Module_ResourceManagement/assets/26480843/81cd3591-2995-4bd0-b4b7-44c0c5c452bf)

**Comment by EleonoraPetzold** [comment]
tested and it works
