### ISSUE TITLE
Edit resource time : end-date changes unexpected

### ISSUE THREAD

**Issue by aostrow** [bexis/Module_ResourceManagement#178]
If you change the "from-date" the "to-date" by itself to "to-date"+1 day
Should stay as it is.

**Comment by geofranzi** [comment]
It ensures end date is always after start ..not sure if this is a bug ....

**Comment by aostrow** [comment]
In the case of "edit" and the end date is after the start date I would prefer to keep the existing value.

**Comment by geofranzi** [comment]
Ok, right. If we would know if we edit or create .... for the Ui it’s the same :(.

**Comment by EleonoraPetzold** [comment]
That endate = startdate +1 is intended. There is no bug. Let discuss it on occasion

**Comment by EleonoraPetzold** [comment]
A user has now said that too. I will change it so that the date remains.

**Comment by EleonoraPetzold** [comment]
It is possible to define the duration time for a resource when it will be booked. (1 day, 2 days, 1 week or 2 hour etc.). The idea here was to set the end date by default to the resource duration. In our case it is 1 day. I remove the auto duration setting but we need to have this function in our mind.
