### ISSUE TITLE
Reasons, for Persons and duration for Copy filled values to all other don't work properly

### ISSUE THREAD

**Issue by bayramliaziz** [bexis/Module_ResourceManagement#185]
- Add two resources that contain Reason and click continue booking 
- Fill in the required fields for the first resource
- Click Copy filled values to all other 
- Edit the Reasons for the second resource

Similar to this:
![err](https://user-images.githubusercontent.com/66725469/109856349-aeb58f80-7c59-11eb-8a94-a3c66059abbe.png)

- Click Book

Result: 

Reasons don't match with the reasons of the previous image.  It seems reasons are connected for these two resources.
![err](https://user-images.githubusercontent.com/66725469/109856991-6fd40980-7c5a-11eb-8266-99766ace72f5.png)

**Comment by EleonoraPetzold** [comment]
not reproducible, solved here: #154

**Comment by EleonoraPetzold** [comment]
the same behavior also with reserved for persons.
