### ISSUE TITLE
Adding persons to a booking

### ISSUE THREAD

**Issue by EleonoraPetzold** [bexis/Module_ResourceManagement#19]
Wenn ich eine Person hinzufüge (Sleeping Place) wird deren Namen nicht gezeigt, 
- [x] name not visible
ab 2. hinzugefügter Person wird show all + man kann mehr Namen als gebuchte Plätze hinzufügen.
By Cornelia
- [ ] more names than places

**Comment by geofranzi** [comment]
" more names than places", we can not prevent this, as we do not know the context. E.g. 2 persons can reserve one metal detector in one reservation if they work together. Maybe we can give a warning, but not more.
