### ISSUE TITLE
Info button in "Shopping Area"

### ISSUE THREAD

**Issue by CFuerstenau** [bexis/Module_ResourceManagement#197]
The info buttons should contain useful information for the explorer, not internal information.
There should be also a mouse over on the info button
![grafik](https://user-images.githubusercontent.com/45873895/114682436-62a54280-9d0f-11eb-8f7a-f5d636b272f6.png)

**Comment by EleonoraPetzold** [comment]
Resources need a meaningful description. This should be provided by the LMTs.

**Comment by CFuerstenau** [comment]
Auf alle Fälle sollte eine Info zum Hausschlüssel mit rein, dass der mitgebucht werden muss.

**Comment by EleonoraPetzold** [comment]
Hausschlüssel zu Schlafplatz? Dafür könnten wir den Dependeny contraints auch mal testen ....

**Comment by EleonoraPetzold** [comment]
This is more an internal issue, move to BEXIS-intern and close here.
