### ISSUE TITLE
Notifications should be editable by admins

### ISSUE THREAD

**Issue by aostrow** [bexis/Module_ResourceManagement#209]
Notification entries are to edit/delete by the originator only. Would be good if:
- admin should be able by default
- groups per explo are able to do

Configure the 2nd via file?

**Comment by EleonoraPetzold** [comment]
> Configure the 2nd via file?

Is already available in settings for the assignment of rights for bookings and schedules.
![image](https://user-images.githubusercontent.com/42029171/130590454-a40f94fe-4042-4c60-81b6-3528b2e2acac.png)
