### ISSUE TITLE
Error if reservation description field is filled with large text

### ISSUE THREAD

**Issue by aostrow** [bexis/Module_ResourceManagement#212]
Problem:
If the description text is too large (I made a test with 280 words) an insert error occurs. 

Solution:
Either restrict the text box length OR release the length restriction in code/db.

![image](https://user-images.githubusercontent.com/26480843/137520968-9c576a8b-36c5-419d-afa3-4581dfcfd22f.png)

**Comment by geofranzi** [comment]
I prefer to increase the description field in the DB. No need to really restrict it to 255. I changed to text. 
- [ ] change in Code
- [x] change in DB
![image](https://user-images.githubusercontent.com/15946467/137528158-9c1ad827-a0c1-4f76-a32a-a2f9e74a9b91.png)
