### ISSUE TITLE
Filter for Select Activities don't work properly

### ISSUE THREAD

**Issue by bayramliaziz** [bexis/Module_ResourceManagement#215]
- Add a resource that contains Reason button
- Click Reason button and click the filter icon for filtering
- For example, type "Conference" in one of the filter fields and click Filter

Result: 

It navigates to this page.
![err](https://user-images.githubusercontent.com/66725469/151769090-79f4469e-5325-42a9-9542-a3b625324392.png)

**Comment by EleonoraPetzold** [comment]
fix with #219
