### ISSUE TITLE
Mobile number only visible to certain groups

### ISSUE THREAD

**Issue by EleonoraPetzold** [bexis/Module_ResourceManagement#233]
due to data privacy

Show only to certain admin groups or person which create the schedule.

**Comment by aostrow** [comment]
I could see the mobile number with my admin and my test account.

**Comment by aostrow** [comment]
Ok, works now.

But it is unclear to me on which roles the access rights are bound. Is it documented anywhere?

**Comment by EleonoraPetzold** [comment]
for the person who creates the reservation and the admin groups. Is described in the issue text here.
https://github.com/bexis/Module_ResourceManagement/blob/882986a7c66ade9f7055b02c89d5c03ae99885d1/Rbm.Settings.xml#L21

We should add it to the admin howto anyway.

**Comment by EleonoraPetzold** [comment]
works and info in readme
