### ISSUE TITLE
Show what has changed in reservation (email)

### ISSUE THREAD

**Issue by geofranzi** [bexis/Module_ResourceManagement#37]

**Comment by EleonoraPetzold** [comment]
Is it meant here that you can see in the mail what has changed in the edit of the reservation?
is this feature still wanted?

**Comment by aostrow** [comment]
I would say a  mail with all the info of the reservation. Like the first mail. Just to have a summary of the latest state of the reservation.

**Comment by EleonoraPetzold** [comment]
> I would say a mail with all the info of the reservation. Like the first mail. Just to have a summary of the latest state of the reservation.

Yes exactly so it is already. So then I will close this issue. if there comes up any other requirements with that issue then create a new issue.
