### ISSUE TITLE
Similar resources check: show only resources of same type

### ISSUE THREAD

**Issue by aostrow** [bexis/Module_ResourceManagement#63]
If resource is taken and I click "Check availability..." only similar types (object OR area OR sleeping places) should appear. But all resources are shown:
![image](https://user-images.githubusercontent.com/26480843/73691484-b9a69500-46d2-11ea-9e27-4337817d9c6c.png)

**Comment by geofranzi** [comment]
Do we really want this list in general? What does it help me, if I see a list of similar resources ..in this case, a list of objects? It only makes sense, if we start to split the sleeping places.  If not, we can remove the function I think. Let's wait for tomorrow, before fixing it.

**Comment by geofranzi** [comment]
will be fixed with #73
