### ISSUE TITLE
Similar resources check: Show occupied times of afffected resouce

### ISSUE THREAD

**Issue by aostrow** [bexis/Module_ResourceManagement#65]
I thought we had a calendar view of the already taken times (+quantities?) of the resource? 
The user need to see which of the dates are already taken.

Somhow like this:
![image](https://user-images.githubusercontent.com/26480843/73692839-6a159880-46d5-11ea-996d-a57301c9ad71.png)

**Comment by geofranzi** [comment]
implemented, but calendar not working see #71
