### ISSUE TITLE
Calendar: Time and quantity filter should indicate status

### ISSUE THREAD

**Issue by aostrow** [bexis/Module_ResourceManagement#66]
It is not clear if I clicked OK or not in the filter. 
Clear does not reset the date entries. "Just" the results.
I suggest to make the buttons "either or" clickable (+ have color indicator).

![image](https://user-images.githubusercontent.com/26480843/73693347-53237600-46d6-11ea-81b9-f8fc1ef12366.png)

**Comment by geofranzi** [comment]
can someone check, if it works correctly now?

**Comment by geofranzi** [comment]
filter removed
