### ISSUE TITLE
Calendar: Date and quantitiy filter gives always the same result

### ISSUE THREAD

**Issue by aostrow** [bexis/Module_ResourceManagement#67]
Why? Are the resources wrongly set up? 
Found out: The filter (click on OK) activates the last selection of the lower checkboxes.

![image](https://user-images.githubusercontent.com/26480843/73693655-e2308e00-46d6-11ea-9ea6-bd7236c040bf.png)

**Comment by aostrow** [comment]
The filter (click on OK) activates the last selection of the lower checkboxes.

**Comment by geofranzi** [comment]
https://github.com/bexis/Module_ResourceManagement/commit/02aa043698e7a9e920f47163546822e12f40652b

**Comment by geofranzi** [comment]
filter  removed
