### ISSUE TITLE
Resource structure seed data: add attribute type "isFile"

### ISSUE THREAD

**Issue by aostrow** [bexis/Module_ResourceManagement#68]
- [x] unsere resource structure muss erweitert werden, mit dem typ "is file"; name: wahrscheinlich einfach File -> habs jetzt wie in b1 Information File genannt.

- [ ] alle resourcen in Bexis1, die eine Datei haben, müssen den Typ gefüllt haben und die Datei muss mit transferiert werden 
=> das ist in seed Data möglich aber mega aufwendig. Ich bin dafür das per Hand zu machen. Einfach schnell File in B1 runter laden und in b2 wieder an die resource hängen und Confirmation auf "on" setzen.

**Comment by EleonoraPetzold** [comment]
ich verschiebe Punkt 2 in Post migration steps (https://github.com/bexis/BExIS-intern/issues/83)
