### ISSUE TITLE
Fullcalendar broken in similar / availibility view

### ISSUE THREAD

**Issue by geofranzi** [bexis/Module_ResourceManagement#71]

**Comment by geofranzi** [comment]
The calendar is shown, but broken:
![image](https://user-images.githubusercontent.com/15946467/73779603-3f871680-478d-11ea-8cff-b4fe73199bbb.png)

**Comment by geofranzi** [comment]
unclear why and how to fix it. Will be deactivated and postponed

**Comment by EleonoraPetzold** [comment]
not relevant up to now and can be closed.
