### ISSUE TITLE
Too many notification mails are send

### ISSUE THREAD

**Issue by geofranzi** [bexis/Module_ResourceManagement#79]

**Comment by EleonoraPetzold** [comment]
I fixed that one mail was sent more then one time to an email address. But we need to check if to many notification mails are sent with overlap attributes.

**Comment by EleonoraPetzold** [comment]
The system exstract all affected schedules and then read all involved people with their mails. With my fix 
I prevent that a user will be notify twice or more. Now I added also for person groups.
