### ISSUE TITLE
Duplicate ID, after copy and add Person

### ISSUE THREAD

**Issue by geofranzi** [bexis/Module_ResourceManagement#82]
![image](https://user-images.githubusercontent.com/15946467/75688576-0369a780-5ca0-11ea-8fc1-f735bf1e2b42.png)

**Comment by EleonoraPetzold** [comment]
Weißt du ob der Index auch gleich war? ich habe es jetzt lokal probiert und alles hat geklappt ohne doppelte toggle id. Es hat allerdings eine übersprungen also 2,3,4 und dann 6.

**Comment by EleonoraPetzold** [comment]
Auch jetzt nicht reproduzierbar:
![image](https://user-images.githubusercontent.com/42029171/92903036-0cdb8580-f422-11ea-99db-a8d6e64f3f16.png)

**Comment by EleonoraPetzold** [comment]
@geofranzi, probier du es noch mal und wenn es dann wieder nicht auftritt schließen wir das Issue erstmal ;)

**Comment by EleonoraPetzold** [comment]
hast du es noch mal probiert? ich konnte es bisher nicht reproduzieren.

**Comment by geofranzi** [comment]
Dass dürfte / könnte das gleiche Problem sein, wenn man die 2. Resource nicht mehr editieren kann. Also auch was, was Aziz hatte.

**Comment by EleonoraPetzold** [comment]
kannst du das issue hier verlinken

**Comment by EleonoraPetzold** [comment]
> Dass dürfte / könnte das gleiche Problem sein, wenn man die 2. Resource nicht mehr editieren kann. Also auch was, was Aziz hatte.

Das issue von Aziz ist ja gelöst. 
Ich hab das Problem auch immer noch nicht reproduzieren können. Ich schließe das issue und wenn sowas wieder auffällt können wir es wieder aufmachen.
