### ISSUE TITLE
Rename resource type "Object"

### ISSUE THREAD

**Issue by CFuerstenau** [bexis/Module_ResourceManagement#90]
- [ ] rename object to equipment
Should we rename resource type Object in Equipment
![grafik](https://user-images.githubusercontent.com/45873895/86342925-90296f80-bc58-11ea-921e-086b89d00810.png)

Another suggestion to rename booking into event or campaign (on the first view I didnt know what was meant.
![grafik](https://user-images.githubusercontent.com/45873895/86358918-962b4a80-bc70-11ea-9b4e-597f0fbab152.png)

**Comment by aostrow** [comment]
discuss with LMTs?

**Comment by geofranzi** [comment]
I would support to rename it to equipment

**Comment by geofranzi** [comment]
I am not supporting renaming Booking to event or campaign "Booking" describes what it is (more general) and not what it could represent like campaign or event.
