### ISSUE TITLE
Booking notification email

### ISSUE THREAD

**Issue by geofranzi** [bexis/Module_ResourceManagement#92]
- [x] revise layout
~~add link to BEXIS~~

**Comment by EleonoraPetzold** [comment]
should something be changed in the mails? @CFuerstenau

**Comment by CFuerstenau** [comment]
There are only small issues which could be changed:

- Contact person: space behind the name, # in front of the telephone number instead of the space: Dxxx Bxxx( xxxx) -> Dxxx Bxxx (#xxxx)
- Reserved for: add name comma separated and without dash

**Comment by EleonoraPetzold** [comment]
remove html table from mail!
